adding jack support. config dialog redesign, using glade.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -921,6 +921,8 @@ GTK_CFLAGS
 GTK_LIBS
 JACK_CFLAGS
 JACK_LIBS
+LIBGLADE_CFLAGS
+LIBGLADE_LIBS
 NO_PREFIX_PACKAGE_DATA_DIR
 PACKAGE_DATA_DIR
 NO_PREFIX_PACKAGE_DOC_DIR
@@ -953,7 +955,9 @@ PKG_CONFIG
 GTK_CFLAGS
 GTK_LIBS
 JACK_CFLAGS
-JACK_LIBS'
+JACK_LIBS
+LIBGLADE_CFLAGS
+LIBGLADE_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1540,6 +1544,7 @@ Optional Features:
   --enable-fast-install[=PKGS]
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --enable-jack           use JACK [default=yes]
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1568,6 +1573,10 @@ Some influential environment variables:
   GTK_LIBS    linker flags for GTK, overriding pkg-config
   JACK_CFLAGS C compiler flags for JACK, overriding pkg-config
   JACK_LIBS   linker flags for JACK, overriding pkg-config
+  LIBGLADE_CFLAGS
+              C compiler flags for LIBGLADE, overriding pkg-config
+  LIBGLADE_LIBS
+              linker flags for LIBGLADE, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -8592,7 +8601,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 8595 "configure"' > conftest.$ac_ext
+  echo '#line 8604 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11170,11 +11179,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11173: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11182: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11177: \$? = $ac_status" >&5
+   echo "$as_me:11186: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11460,11 +11469,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11463: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11472: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11467: \$? = $ac_status" >&5
+   echo "$as_me:11476: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11564,11 +11573,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11567: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11576: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11571: \$? = $ac_status" >&5
+   echo "$as_me:11580: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13941,7 +13950,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13944 "configure"
+#line 13953 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14041,7 +14050,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 14044 "configure"
+#line 14053 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16442,11 +16451,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16445: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16454: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16449: \$? = $ac_status" >&5
+   echo "$as_me:16458: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16546,11 +16555,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16549: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16558: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16553: \$? = $ac_status" >&5
+   echo "$as_me:16562: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18144,11 +18153,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18147: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18156: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:18151: \$? = $ac_status" >&5
+   echo "$as_me:18160: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -18248,11 +18257,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:18251: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:18260: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:18255: \$? = $ac_status" >&5
+   echo "$as_me:18264: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20468,11 +20477,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20471: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20480: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20475: \$? = $ac_status" >&5
+   echo "$as_me:20484: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20758,11 +20767,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20761: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20770: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20765: \$? = $ac_status" >&5
+   echo "$as_me:20774: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20862,11 +20871,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20865: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20874: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20869: \$? = $ac_status" >&5
+   echo "$as_me:20878: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -23787,6 +23796,17 @@ fi
 
 
 
+# Check whether --enable-jack was given.
+if test "${enable_jack+set}" = set; then
+  enableval=$enable_jack;
+    if test "x$enableval" != "xno"; then
+      usejack=yes
+    fi
+
+fi
+
+
+if test "x$usejack" = "xyes"; then
 
 pkg_failed=no
 { echo "$as_me:$LINENO: checking for JACK" >&5
@@ -23797,12 +23817,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_JACK_CFLAGS="$JACK_CFLAGS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"jack >= 0.100.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "jack >= 0.100.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"jack >= 0.102.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "jack >= 0.102.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_JACK_CFLAGS=`$PKG_CONFIG --cflags "jack >= 0.100.0" 2>/dev/null`
+  pkg_cv_JACK_CFLAGS=`$PKG_CONFIG --cflags "jack >= 0.102.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -23815,12 +23835,12 @@ if test -n "$PKG_CONFIG"; then
         pkg_cv_JACK_LIBS="$JACK_LIBS"
     else
         if test -n "$PKG_CONFIG" && \
-    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"jack >= 0.100.0\"") >&5
-  ($PKG_CONFIG --exists --print-errors "jack >= 0.100.0") 2>&5
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"jack >= 0.102.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "jack >= 0.102.0") 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; then
-  pkg_cv_JACK_LIBS=`$PKG_CONFIG --libs "jack >= 0.100.0" 2>/dev/null`
+  pkg_cv_JACK_LIBS=`$PKG_CONFIG --libs "jack >= 0.102.0" 2>/dev/null`
 else
   pkg_failed=yes
 fi
@@ -23839,14 +23859,14 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        JACK_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "jack >= 0.100.0"`
+	        JACK_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "jack >= 0.102.0"`
         else
-	        JACK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "jack >= 0.100.0"`
+	        JACK_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "jack >= 0.102.0"`
         fi
 	# Put the nasty error message in config.log where it belongs
 	echo "$JACK_PKG_ERRORS" >&5
 
-	{ { echo "$as_me:$LINENO: error: Package requirements (jack >= 0.100.0) were not met:
+	{ { echo "$as_me:$LINENO: error: Package requirements (jack >= 0.102.0) were not met:
 
 $JACK_PKG_ERRORS
 
@@ -23857,7 +23877,7 @@ Alternatively, you may set the environment variables JACK_CFLAGS
 and JACK_LIBS to avoid the need to call pkg-config.
 See the pkg-config man page for more details.
 " >&5
-echo "$as_me: error: Package requirements (jack >= 0.100.0) were not met:
+echo "$as_me: error: Package requirements (jack >= 0.102.0) were not met:
 
 $JACK_PKG_ERRORS
 
@@ -23898,8 +23918,123 @@ else
 echo "${ECHO_T}yes" >&6; }
 	:
 fi
-CFLAGS="$CFLAGS -DHAVEJACK $JACK_CFLAGS"
-LIBS="$LIBS -DHAVEJACK $JACK_LIBS"
+  CFLAGS="$CFLAGS -DHAVEJACK $JACK_CFLAGS"
+  LIBS="$LIBS -DHAVEJACK $JACK_LIBS"
+fi
+
+
+pkg_failed=no
+{ echo "$as_me:$LINENO: checking for LIBGLADE" >&5
+echo $ECHO_N "checking for LIBGLADE... $ECHO_C" >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBGLADE_CFLAGS"; then
+        pkg_cv_LIBGLADE_CFLAGS="$LIBGLADE_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libglade-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libglade-2.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBGLADE_CFLAGS=`$PKG_CONFIG --cflags "libglade-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$LIBGLADE_LIBS"; then
+        pkg_cv_LIBGLADE_LIBS="$LIBGLADE_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { (echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"libglade-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "libglade-2.0") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_LIBGLADE_LIBS=`$PKG_CONFIG --libs "libglade-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        LIBGLADE_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "libglade-2.0"`
+        else
+	        LIBGLADE_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "libglade-2.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$LIBGLADE_PKG_ERRORS" >&5
+
+	{ { echo "$as_me:$LINENO: error: Package requirements (libglade-2.0) were not met:
+
+$LIBGLADE_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LIBGLADE_CFLAGS
+and LIBGLADE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+echo "$as_me: error: Package requirements (libglade-2.0) were not met:
+
+$LIBGLADE_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables LIBGLADE_CFLAGS
+and LIBGLADE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LIBGLADE_CFLAGS
+and LIBGLADE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables LIBGLADE_CFLAGS
+and LIBGLADE_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+else
+	LIBGLADE_CFLAGS=$pkg_cv_LIBGLADE_CFLAGS
+	LIBGLADE_LIBS=$pkg_cv_LIBGLADE_LIBS
+        { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	:
+fi
+
+
 
 if test "x${prefix}" = "xNONE"; then
 
@@ -23989,7 +24124,7 @@ _ACEOF
 
 
 
-ac_config_files="$ac_config_files Makefile po/Makefile.in src/Makefile pixmaps/Makefile lingot.desktop"
+ac_config_files="$ac_config_files Makefile po/Makefile.in src/Makefile src/glade/Makefile pixmaps/Makefile lingot.desktop"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -24607,6 +24742,7 @@ do
     "Makefile") CONFIG_FILES="$CONFIG_FILES Makefile" ;;
     "po/Makefile.in") CONFIG_FILES="$CONFIG_FILES po/Makefile.in" ;;
     "src/Makefile") CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
+    "src/glade/Makefile") CONFIG_FILES="$CONFIG_FILES src/glade/Makefile" ;;
     "pixmaps/Makefile") CONFIG_FILES="$CONFIG_FILES pixmaps/Makefile" ;;
     "lingot.desktop") CONFIG_FILES="$CONFIG_FILES lingot.desktop" ;;
     "po/stamp-it") CONFIG_COMMANDS="$CONFIG_COMMANDS po/stamp-it" ;;
@@ -24867,6 +25003,8 @@ GTK_CFLAGS!$GTK_CFLAGS$ac_delim
 GTK_LIBS!$GTK_LIBS$ac_delim
 JACK_CFLAGS!$JACK_CFLAGS$ac_delim
 JACK_LIBS!$JACK_LIBS$ac_delim
+LIBGLADE_CFLAGS!$LIBGLADE_CFLAGS$ac_delim
+LIBGLADE_LIBS!$LIBGLADE_LIBS$ac_delim
 NO_PREFIX_PACKAGE_DATA_DIR!$NO_PREFIX_PACKAGE_DATA_DIR$ac_delim
 PACKAGE_DATA_DIR!$PACKAGE_DATA_DIR$ac_delim
 NO_PREFIX_PACKAGE_DOC_DIR!$NO_PREFIX_PACKAGE_DOC_DIR$ac_delim
@@ -24881,7 +25019,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 69; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 71; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
